Repository Pro-Digital-Academy-Frontend-Project/Backend, pull requests merged in 2024-12, with the labels that each got.

#69 #68 Refactor : 토큰 갱신 함수 수정
  app.js
  controllers/keywordController.js
  services/tokenService.js
Labels: 🔨 Refactor

#70 version 0.4.1
  app.js
  controllers/keywordController.js
  services/tokenService.js
Labels: 🌏 CI/CD

#72 #71 Refactor : 차트 데이터 가져오는 날짜 변경
  controllers/chartController2.js
Labels: 🔨 Refactor

#75 #74 Refactor : 키워드에 대한 종목 랭킹 반환 데이터 변경
  services/keywordService.js
  services/tokenService.js
Labels: 🔨 Refactor

#76 version 0.4.2
  controllers/chartController2.js
  services/keywordService.js
  services/tokenService.js
Labels: 🌏 CI/CD

#79 #73 Feat: 뉴스 크롤링 api 구현
  app.js
  controllers/newsController.js
  package.json
  routes/newsRoutes.js
  services/newsService.js
Labels: ✨ Feature

#81 #80 Feat : 가중치 합이 가장 높은 종목 조회 API
  controllers/searchController.js
  routes/stockRoutes.js
Labels: ✨ Feature

#83 #73 Feat: 크롤링 검색 키워드 변경
  services/newsService.js
Labels: ✨ Feature

#85 #84 Refactor : 차트 데이터 캐싱 및 재시도 알고리즘 구현
  controllers/chartController.js
Labels: 🔨 Refactor

#87 #86 Refactor : 키워드 종합 랭킹에서 keyword_id도 반환하도록 수정
  services/keywordService.js
Labels: 🔨 Refactor

#88 Version 0.5.1
  app.js
  controllers/chartController.js
  controllers/chartController2.js
  controllers/newsController.js
  controllers/searchController.js
  controllers/slackScheduler.js
  package.json
  routes/newsRoutes.js
  routes/stockRoutes.js
  services/keywordService.js
  services/newsService.js
  services/slackService.js
  swagger.js
Labels: 🌏 CI/CD

#90 #89 Feat: 채팅 메시지 보내기 api 응답값 추가
  controllers/chatController.js
Labels: ✨ Feature

#91 Version 0.5.2
  controllers/chatController.js
Labels: 🌏 CI/CD

#92 Version 1.0.0
  controllers/chatController.js
  controllers/postToken.js
  controllers/searchController.js
  controllers/userController.js
  controllers/userKeywordController.js
  services/keywordService.js
  services/slackService.js
  socket/socketHandler.js
Labels: 🌏 CI/CD, 🔨 Refactor

#94 #93 Refactor : ElasticSearch 도입 및 키워드 API 수정
  app.js
  controllers/keywordController.js
  elasticSearch.js
  package.json
  routes/keywordRoutes.js
  services/elasticSearchService.js
  services/keywordService.js
  services/tokenService.js
Labels: 🔨 Refactor

#95 #93 Refactor : ElasticSearch 도입 및 키워드 API 수정
  app.js
  controllers/keywordController.js
  elasticSearch.js
  package.json
  routes/keywordRoutes.js
  services/elasticSearchService.js
  services/keywordService.js
  services/tokenService.js
Labels: 🔨 Refactor
