Repository Pro-Digital-Academy-Frontend-Project/Backend, pull requests merged in 2024-11, with the labels that each got.

#3 #2 Setting: MVC 설계
  controllers/exampleControllers.js
  models/exampleModel.js
  routes/exampleRoutes.js
Labels: ⚙ Setting

#9 #7 Feat : ORM을 통한 테이블 자동 생성
  .github/workflows/deploy.yml
  README.md
  app.js
  db.js
  models/Chat_Room.js
  models/Chat_Room_Message.js
  models/Chat_Room_Message_Like.js
  models/Keyword.js
  models/Stock.js
  models/User.js
  models/User_Keyword.js
  models/User_Stock.js
  models/exampleModel.js
  models/index.js
  package-lock.json
  package.json
Labels: ✨ Feature

#12 #10 feat user api
  controllers/userController.js
  controllers/userKeywordController.js
  controllers/userStockController.js
  models/userModel.js
  node_modules/.bin/color-support
  node_modules/.bin/mime
  node_modules/.bin/mkdirp
  node_modules/.bin/node-pre-gyp
  node_modules/.bin/nopt
  node_modules/.bin/rimraf
  node_modules/.bin/semver
  node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  node_modules/make-dir/node_modules/.bin/semver
  routes/userRoutes.js
Labels: ✨ Feature

#18 #16 Refactor : DB 구조 변경
  models/User_Keyword.js
  models/index.js
Labels: 🔨 Refactor

#20 #19 Setting : Swagger 추가
  app.js
  package.json
  swagger-output.json
  swagger.js
Labels: ⚙ Setting

#22 #21 Feat : 특정 글자로 시작하는 키워드 검색 TOP 10 조회
  app.js
  controllers/keywordController.js
  routes/keywordRoutes.js
  services/keywordService.js
  swagger-output.json
Labels: ✨ Feature

#24 Fix/#10 chart api
  app.js
  controllers/chartController.js
  routes/chartRoutes.js
Labels: 🐞 BugFix

#28 Fix/#27 user stock api delete
  .github/workflows/deploy.yml
  .gitignore
  README.md
  app.js
  controllers/allStocksController.js
  controllers/chartController.js
  controllers/chatController.js
  controllers/keywordController.js
  controllers/searchController.js
  controllers/userController.js
  controllers/userKeywordController.js
  controllers/userStockController.js
  db.js
  middleware/authMiddleware.js
  models/Chat_Room.js
  models/Chat_Room_Message.js
  models/Chat_Room_Message_Like.js
  models/Keyword.js
  models/Stock.js
  models/User.js
  models/User_Keyword.js
  models/User_Stock.js
  models/chatModel.js
  models/exampleModel.js
  models/index.js
  package-lock.json
  package.json
  routes/chat.js
  routes/index.js
  routes/keywordRoutes.js
  routes/stockRoutes.js
  routes/userRoutes.js
  routes/users.js
  services/keywordService.js
  swagger-output.json
  swagger.js
Labels: 🐞 BugFix

#30 Fix/#27 user stock api
  controllers/chartController.js
  controllers/userKeywordController.js
  controllers/userStockController.js
  routes/userRoutes.js
  swagger-output.json
Labels: ✨ Feature

#34 #12 Feat: 소켓 채팅 구현
  bin/www
  controllers/chatController.js
  package.json
  routes/chat.js
  socket/socketHandler.js
  swagger-output.json
Labels: ✨ Feature

#37 #36 Refactor : 키워드 관련 API 최대 개수 변경
  services/keywordService.js
Labels: 🔨 Refactor

#39 Feat/#27 user stock api #33
  controllers/chartController2.js
  controllers/searchController.js
  controllers/userStockController.js
  routes/stockRoutes.js
  services/keywordService.js
Labels: ✨ Feature

#40 #12 Feat: 채팅 메시지 nickname 보이도록 수정
  controllers/chatController.js
  models/index.js
  socket/socketHandler.js
Labels: ✨ Feature

#41 feat/#27: stock id로 조회, stock name으로 조회 api 경로 수정
  controllers/searchController.js
  routes/stockRoutes.js
Labels: 🐞 BugFix

#44 Refactor/#42 search stock
  controllers/exampleControllers.js
  controllers/searchController.js
  routes/exampleRoutes.js
Labels: 🔨 Refactor

#46 Refactor#45
  app.js
  package.json
Labels: 🔨 Refactor

#47 version 0.1.1
  app.js
  controllers/exampleControllers.js
  controllers/searchController.js
  routes/exampleRoutes.js
Labels: 🌏 CI/CD

#48 #45 Refactor : API 경로 수정
  app.js
Labels: 🔨 Refactor

#49 version 0.1.3
  app.js
Labels: 🔨 Refactor

#51 feat(#50): 즐겨찾기 별 키워드/종목 랭킹 조회 API 구현
  controllers/userKeywordController.js
  controllers/userStockController.js
  routes/userRoutes.js
Labels: ✨ Feature

#53 feat(#52): nickname, slack_id를 반환하는 api 구현
  controllers/chartController2.js
  controllers/userController.js
  routes/userRoutes.js
Labels: ✨ Feature

#57 version 0.2.1
  controllers/chartController2.js
  controllers/userController.js
  controllers/userKeywordController.js
  controllers/userStockController.js
  routes/stockRoutes.js
  routes/userRoutes.js
Labels: 🌏 CI/CD

#60 #58 Feat : 키워드 API 추가
  controllers/chartController2.js
  controllers/keywordController.js
  routes/keywordRoutes.js
  services/keywordService.js
Labels: ✨ Feature

#62 #61 Feat : 랜딩 페이지 사이드바 (종목) API
  controllers/userStockController.js
  routes/userRoutes.js
  services/keywordService.js
Labels: ✨ Feature

#65 version 0.3.1
  .prettierignore
  controllers/chartController2.js
  controllers/chatController.js
  controllers/keywordController.js
  controllers/userController.js
  controllers/userKeywordController.js
  controllers/userStockController.js
  package.json
  routes/chat.js
  routes/keywordRoutes.js
  routes/userRoutes.js
  services/keywordService.js
Labels: 🌏 CI/CD

#67 #63 Refactor : 채팅, 토큰 URL 수정
  app.js
  controllers/chartController2.js
  services/tokenService.js
Labels: 🔨 Refactor
